#!/bin/sh
#
# macchiato - batch marking utility

usage () {
    cat <<EOF
Usage:
        macchiato key file...

Dependencies:
        python-docx2txt
EOF
    exit 1
}

bail () {
    printf "Error:\t%s" "$@"
    exit 1
}

# process arguments
[ $# -lt 2 ] && usage
if [ -e "$1" ]; then 
    key="$1"
    shift
else
    bail "Answer key not found\n"
fi

# set up directories & records
processed="./processed"
[ -e $processed ] || mkdir $processed
outfile="./marks"
[ -e $outfile ] && cp "$outfile" "${outfile}-old"
printf "" > $outfile

for file in "$@"; do
    basename=${file##*/}
    # convert from different formats to plaintext
    case $file in
        *.docx)
            command -v docx2txt >/dev/null || bail "Please install python-docx2txt"
            stem=${basename%%.docx}
            docx2txt "$file" "$processed/$stem"
        ;;
        *)
            cp "$file" "$processed/$basename"
        ;;
    esac
done

for file in "$processed"/*; do
    sed -i '
        /^\s*$/d; # empty lines
        s/^\s*\(.*\)$/\1/g; # leading whitespace
        s/\(^[[:digit:]]\{1,2\}\).*\(\w\).*$/\1\2/g;
        /^[^[:digit:]]/d;
        ' "$file"
    mistakes=$(diff -y --suppress-common-lines "$key" "$file" | wc -l)
    printf "%s %s\n" "$file" "$mistakes" >> "$outfile"
done
